include ../../makevars.in

TARGET  = calc_diff

SRC     = $(notdir $(wildcard *.cc))
OBJS    = $(addsuffix .o, $(basename $(SRC)))  

DESTDIR = $(TOPDIR)/install/tools

include $(TOPDIR)/makerules.in
